# -*- coding: utf-8 -*-
"""Hello World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RMZL15mZMI7gIfth3CC8n-DMaPVxOKh5
"""

print("Hello, World!")