# -*- coding: utf-8 -*-
"""Vending Machine Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RMZL15mZMI7gIfth3CC8n-DMaPVxOKh5
"""

# Coffee Vending Machine

print("Welcome to the Coffee Vending Machine!")

# Taking user input for sugar, milk, and coffee strength
sugar = input("Would you like to add sugar? (yes/no): ").lower()
milk = input("Would you like to add milk? (yes/no): ").lower()
strength = input("How strong do you want your coffee? (light/medium/strong): ").lower()

# Output order confirmation
print("Your order is ready")